### ISSUE TITLE
Disable/Hide RP when idling

### ISSUE THREAD

**Issue by AtakaJak** [pandier/intellij-discord-rp#100]
### What's missing?

Hi, thanks for making this plugin.

When Un-Focusing the IDE it would awesome if the RP could be stopped temporarily until the IDE is refocused. This allows games or other apps that use RP to be shown instead if you need to keep the editor open or are just switching between often.

There's a VSCode plugin that does this, by allowing an "Idle Timeout" when greater than 0 will hide it's RP when inactive for longer than the specified number of seconds.

https://github.com/iCrawl/discord-vscode

**Comment by pandier** [comment]
How precise do you need the setting for the timeout to be? The developed setting is currently defined in minutes, with the shortest amount of time being 1 minute.
