### ISSUE TITLE
Setting to display IntelliJ version (Ultimate or community)

### ISSUE THREAD

**Issue by The-Dumb-Dino** [pandier/intellij-discord-rp#103]
### What's missing?

The previous plugin I used that broke after a while supported this and I think it'd be nice here as well.

Also really love this one btw, the icons feel more modern than the other ones you find on the marketplace. Keep up the great work.

**Comment by The-Dumb-Dino** [comment]
<img width="212" alt="Bildschirmfoto 2024-11-26 um 16 36 24" src="https://github.com/user-attachments/assets/7eeb81e1-dc4a-4180-bf4c-a67d1c07000b">
Well It exists more or less, but I mean the main title actually.

**Comment by pandier** [comment]
Do you mean the application name at the top?

![test](https://github.com/user-attachments/assets/7b0b51d7-d0d7-43bb-a050-e92205466e81)

**Comment by The-Dumb-Dino** [comment]
> Do you mean the application name at the top?
> 
> ![test](https://github.com/user-attachments/assets/7b0b51d7-d0d7-43bb-a050-e92205466e81)

Yea exactly that one. Would be nice if it was adjustable too

**Comment by pandier** [comment]
Sadly the only way to adjust that is by making a custom Discord application through their Developer platform, setting the name there and using the id of that application, but I'll add a setting for showing the full name.

**Comment by The-Dumb-Dino** [comment]
> Sadly the only way to adjust that is by making a custom Discord application through their Developer platform, setting the name there and using the id of that application, but I'll add a setting for showing the full name.

Thank you very much, love this project.

**Comment by pandier** [comment]
Implemented in `1.6.2`. Update will be available in ~2 business days.
