### ISSUE TITLE
Repository button in Rich Presence

### ISSUE THREAD

**Issue by pandier** [pandier/intellij-discord-rp#11]

**Comment by pandier** [comment]
There needs to be a discussion about privacy before implementing this. Some repositories can be private and this feature could be a privacy issue. Should the repository button be visible in a project by default and then turned off by a setting or should it be the other way around?

My current idea, which I think works the best, is having the button turned off globally by default, but the user can enable it either for all projects (and blacklist some) or for certain projects only.

**Comment by Cleboost** [comment]
I think it's best if it's deactivated by default, as you said, and can be activated for each project you want. Buttons could have several mods (github, custom url, other ??)
