### ISSUE TITLE
Language support for dart

### ISSUE THREAD

**Issue by dohun0310** [pandier/intellij-discord-rp#35]
- Language: Dart
![dart](https://github.com/pandier/intellij-discord-rp/assets/63141348/637c0245-20dd-488b-8a44-b33fb41c604b)
I've created an icon for darts. Can I add support for darts? Also, could you please add android studio?

**Comment by dohun0310** [comment]
![android_studio](https://github.com/pandier/intellij-discord-rp/assets/63141348/dcefdcc7-fc97-40f6-bd2a-e2ab963e5606)
This is icon for android studio. I've been fork around with getting Android Studio to support it on my own, but it doesn't seem like something I can do on my own.

**Comment by pandier** [comment]
Support for Android Studio has been added in #28 and will be featured in version **1.1**.

**Comment by dohun0310** [comment]
Got it! Thank you for your works :)

**Comment by pandier** [comment]
I will be planning on adding Dart, the progress will be tracked by this issue.

**Comment by pandier** [comment]
I made this icon for Dart and I think it looks better. It's inspired (but different) from the [Simple Icons' Dart icon](https://simpleicons.org/?q=dart).

<img height="256px" alt="dart-icon" src="https://github.com/pandier/intellij-discord-rp/assets/62116820/1eef7bdd-9046-4703-b19e-02e9459753a0"/>

**Comment by dohun0310** [comment]
> I made this icon for Dart and I think it looks better. It's inspired (but different) from the [Simple Icons' Dart icon](https://simpleicons.org/?q=dart).
> 
> @dohun0310 what are your opinions on this?
> 
> <img alt="dart-icon" height="256px" src="https://private-user-images.githubusercontent.com/62116820/322204251-1eef7bdd-9046-4703-b19e-02e9459753a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMTA1MDAsIm5iZiI6MTcxMzAxMDIwMCwicGF0aCI6Ii82MjExNjgyMC8zMjIyMDQyNTEtMWVlZjdiZGQtOTA0Ni00NzAzLWIxOWUtMDJlOTQ1OTc1M2EwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDEyMTAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2YTk2YzdkZDI4YTU5Y2EzNGRiNDIxN2U4ZmIwYmE1MDMyMTA0NDU4OWM4ODZmYjJjMGY1OTI5ZmYyY2Q0ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UW5ByuVDLtI5IecVeE-ORrDFS1OadmKyLbQKXBf9LOY">

That's look great

**Comment by dohun0310** [comment]
https://en.wikipedia.org/wiki/File:Dart-logo.png
My icon is inspired by this.

**Comment by pandier** [comment]
> > I made this icon for Dart and I think it looks better. It's inspired (but different) from the [Simple Icons' Dart icon](https://simpleicons.org/?q=dart).
> > @dohun0310 what are your opinions on this?
> > <img alt="dart-icon" height="256px" src="https://private-user-images.githubusercontent.com/62116820/322204251-1eef7bdd-9046-4703-b19e-02e9459753a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMTA1MDAsIm5iZiI6MTcxMzAxMDIwMCwicGF0aCI6Ii82MjExNjgyMC8zMjIyMDQyNTEtMWVlZjdiZGQtOTA0Ni00NzAzLWIxOWUtMDJlOTQ1OTc1M2EwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDEyMTAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2YTk2YzdkZDI4YTU5Y2EzNGRiNDIxN2U4ZmIwYmE1MDMyMTA0NDU4OWM4ODZmYjJjMGY1OTI5ZmYyY2Q0ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UW5ByuVDLtI5IecVeE-ORrDFS1OadmKyLbQKXBf9LOY">
> 
> That's look great

I will then add my version, if that's fine by you?

**Comment by dohun0310** [comment]
> > > I made this icon for Dart and I think it looks better. It's inspired (but different) from the [Simple Icons' Dart icon](https://simpleicons.org/?q=dart).
> > > @dohun0310 what are your opinions on this?
> > > <img alt="dart-icon" height="256px" src="https://private-user-images.githubusercontent.com/62116820/322204251-1eef7bdd-9046-4703-b19e-02e9459753a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMTA1MDAsIm5iZiI6MTcxMzAxMDIwMCwicGF0aCI6Ii82MjExNjgyMC8zMjIyMDQyNTEtMWVlZjdiZGQtOTA0Ni00NzAzLWIxOWUtMDJlOTQ1OTc1M2EwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDEyMTAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2YTk2YzdkZDI4YTU5Y2EzNGRiNDIxN2U4ZmIwYmE1MDMyMTA0NDU4OWM4ODZmYjJjMGY1OTI5ZmYyY2Q0ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UW5ByuVDLtI5IecVeE-ORrDFS1OadmKyLbQKXBf9LOY">
> > 
> > 
> > That's look great
> 
> I will then add my version, if that's fine by you?

Yes!

**Comment by pandier** [comment]
Language support for Dart has been implemented and will be available in the upcoming **1.1** release.

I will also delay some features that were supposed to come with the release to make sure this feature can be used as soon as possible.

**Comment by dohun0310** [comment]
Awesome! I can't wait

**Comment by dohun0310** [comment]
<img width="603" alt="image" src="https://github.com/pandier/intellij-discord-rp/assets/63141348/6f6f3688-315d-4092-8880-c278b80809cb">
I try your new feature. This is very cool.
