### ISSUE TITLE
I want to add text field variables.

### ISSUE THREAD

**Issue by Shihyeon** [pandier/intellij-discord-rp#40]
**Replace this** with a clear and concise description of the feature that you are requesting. If the feature is related to a problem, also describe the problem.

I want to add text field variables.

`{app_version}`: Version of the IDE
`{app_edition}`: Edition of the IDE
`{module_name}` or `{directory_name}`: Name of the current module(directory)
`{file_size}`: Size of the current file

**Comment by pandier** [comment]
`{app_version}` is easy enough to add.
Not sure how `{app_edition}` would work, because IDEs like WebStorm don't have an edition.
Not sure what you mean with `{module_name}`, a project can have multiple modules, do you mean the one that is currently being edited?
`{file_size}` may be harder to implement, but not impossible.

**Comment by Shihyeon** [comment]
App edition refers to community edition and ultimate edition. If it is difficult to include it to maintain compatibility with other IDEs, I don't think it is necessary to include it.
`{module_name}` is the module currently being edited.
If `{file_size}` is difficult to implement, it is okay to not include it. This is what I want, but it is your right to produce and distribute it.
Thank you for making this open source plugin.

(The text may be strange because I used a translator.)

**Comment by pandier** [comment]
Perhaps `{app_full_name}` could include the app name with the edition **without** the version:

- `{app_name}` = IntelliJ IDEA
- `{app_full_name}` = IntelliJ IDEA Community 
- `{app_full_name} {app_version}` = IntelliJ IDEA Community 2024.1

For apps that don't have an edition, `{app_full_name}` would include only the app name:

- `{app_name}` = WebStorm
- `{app_full_name}` = WebStorm

Also, what if no modules are currently being edited? Should the name be the project name? Could you maybe describe in detail how it would work so I can understand it better and implement it correctly?

**Comment by Shihyeon** [comment]
```
Perhaps {app_full_name} could include the app name with the edition without the version:

{app_name} = IntelliJ IDEA
{app_full_name} = IntelliJ IDEA Community
{app_full_name} {app_version} = IntelliJ IDEA Community 2024.1
For apps that don't have an edition, {app_full_name} would include only the app name:

{app_name} = WebStorm
{app_full_name} = WebStorm
```
good

```
Also, what if no modules are currently being edited? Should the name be the project name? Could you maybe describe in detail how it would work so I can understand it better and implement it correctly?
```

Different from `{project_name}`. More precisely, I think the directory name would be more correct than the module name. The directory where the current file is located.

(I'm using a vscode extension that has a similar feel to this plugin. https://github.com/LeonardSSH/vscord)

**Comment by pandier** [comment]
What about naming it `{file_directory}` or `{file_directory_name}` instead?
Which one do you think would be better?

**Comment by Shihyeon** [comment]
`{file_directory}` better then

**Comment by pandier** [comment]
The pull request has been merged and the variables will be avalible in the next **1.1** release.
