### ISSUE TITLE
Audio, image, compressed file support

### ISSUE THREAD

**Issue by dohun0310** [pandier/intellij-discord-rp#41]
When using JetBrains IDE to open audio and image compressed files, this plugin cannot show these files in Discord. Support for such files is necessary. I request that the plugin be updated to support recognizing file extensions such as .ogg, .aac, .mp3 as audio files, and .svg, .png as image files, as well as .zip, .7z as compressed files.

**Comment by pandier** [comment]
I will start work on the design for the icons

**Comment by pandier** [comment]
I'm not sure about the utilization of icons for compressed files. Can you even open compressed files in IntelliJ IDEs? Can you give me some examples how it would be used, in what scenarios?

**Comment by dohun0310** [comment]
Sorry for the confusion, it's a mix-up with `vsc`.

**Comment by pandier** [comment]
IntelliJ also apparently doesn't handle audio files

**Comment by dohun0310** [comment]
I can do this with a plugin, but I don't think it's important, so you don't need support it.
