### ISSUE TITLE
Emoji support

### ISSUE THREAD

**Issue by Cleboost** [pandier/intellij-discord-rp#50]
### What's missing?

Allow the usage of emoji in status

![image](https://github.com/pandier/intellij-discord-rp/assets/61158869/01568966-2ea4-433d-ad36-1a3b713a2ad5)
![image](https://github.com/pandier/intellij-discord-rp/assets/61158869/16e852c9-ac3f-41d1-9116-da3182ece648)

**Comment by pandier** [comment]
I'm wondering if this is an issue with the current IPC implementation. Do you have an example of the emojis working in a Rich Presence?

**Comment by pandier** [comment]
Okay, I'll look into that. We're gonna be switching to a different back-end in #17 which might resolve this.

**Comment by pandier** [comment]
Will be available in **1.2** release.
