### ISSUE TITLE
Better menu access

### ISSUE THREAD

**Issue by Cleboost** [pandier/intellij-discord-rp#57]
### What's missing?

Move the page to a menu below Advanced to avoid having to go to submenus and be more visible.

![image](https://github.com/pandier/intellij-discord-rp/assets/61158869/e6bb812b-eabd-4a5e-83f4-3d5b0195f365)

**Comment by pandier** [comment]
I'm not sure about this change, because if all plugins did this, then it could become cluttered. Requires more discussion.

**Comment by Cleboost** [comment]
Yes, but few plugins do this. In any case, I think it's out of place in the tool category.
