### ISSUE TITLE
Icon request for VueJS

### ISSUE THREAD

**Issue by Cleboost** [pandier/intellij-discord-rp#58]
https://vuejs.org

![image](https://github.com/pandier/intellij-discord-rp/assets/61158869/9dc76eff-bd8f-4f2b-b39f-3547be467577)

**Comment by Cleboost** [comment]
https://github.com/pandier/intellij-discord-rp/pull/60

**Comment by pandier** [comment]
This is my proposed design:

![vuejs](https://github.com/pandier/intellij-discord-rp/assets/62116820/74261e56-9639-490b-b6e4-460a4bc5e12b)

**Comment by Cleboost** [comment]
The green is not the same of original icon
I prefer my own but you are the owner x)

![image](https://github.com/pandier/intellij-discord-rp/assets/61158869/f7a746b5-006c-4089-9a5a-044a92b9cff4)

**Comment by pandier** [comment]
You're right, it should be more bluish. This is my new proposed design (didn't use the exact color but tried to match it):

![vuejs](https://github.com/pandier/intellij-discord-rp/assets/62116820/422e3756-6cce-42b9-89d0-23c04802474b)

**Comment by Cleboost** [comment]
Yes it's better I think

**Comment by pandier** [comment]
Will be available in **1.3**.
