### ISSUE TITLE
File line count variable

### ISSUE THREAD

**Issue by Cleboost** [pandier/intellij-discord-rp#59]
### What's missing?

A variable containing the line number of the currently open file (`{file_lines_count}`)

**Comment by pandier** [comment]
Related to #48, which means I'm not currently sure how to implement this.

**Comment by pandier** [comment]
I've done some research and now I know how to do this. Going to implement it later.

**Comment by pandier** [comment]
The current problem is that certain files (or specifically the editor of the file) don't have line counts, like images for example. What should happen in this scenario? Should we just show an `x` or some other character?

**Comment by Cleboost** [comment]
Good question... Let me think about it

**Comment by pandier** [comment]
I'll just use the hyphen (`-`) for now

**Comment by Cleboost** [comment]
Nice
