### ISSUE TITLE
Icon request for tsconfig.json

### ISSUE THREAD

**Issue by Cleboost** [pandier/intellij-discord-rp#62]
This is a special icon for config ts. I think it would be nice not to use the normal json icon.

![image](https://github.com/pandier/intellij-discord-rp/assets/61158869/f6d1195f-af21-43d1-bdb0-cf1dc6036993)
![image](https://github.com/pandier/intellij-discord-rp/assets/61158869/da95e1b2-b037-4b3c-b84d-75d98b5a7613)
![image](https://github.com/pandier/intellij-discord-rp/assets/61158869/c8804ec2-4d72-4e96-9694-a7d5541e620e)

**Comment by pandier** [comment]
This is my proposed design:

![tsconfig256](https://github.com/pandier/intellij-discord-rp/assets/62116820/27a9fe56-8795-4c60-a1b3-3d427ad71d22)

**Comment by Cleboost** [comment]
Clean
