### ISSUE TITLE
Icon request for npm

### ISSUE THREAD

**Issue by Cleboost** [pandier/intellij-discord-rp#63]
![image](https://github.com/pandier/intellij-discord-rp/assets/61158869/2ccc69d5-8eea-451b-96cd-6517ef449f56)
![image](https://github.com/pandier/intellij-discord-rp/assets/61158869/c5e3e1b3-4426-4f83-b5bf-312ac65cf112)
![image](https://github.com/pandier/intellij-discord-rp/assets/61158869/c3196a16-da03-4bdd-86e5-e6c9d159584d)

**Comment by Cleboost** [comment]
Perfect

**Comment by Cleboost** [comment]
package-lock.json has same icon
![image](https://github.com/pandier/intellij-discord-rp/assets/61158869/bfe85222-43eb-4c11-8d71-600a231e4ac1)

**Comment by pandier** [comment]
What do you think should be the name of the type?
I'm thinking of just calling it **Package.json**.
