### ISSUE TITLE
Change the C# file icon please

### ISSUE THREAD

**Issue by DenianRamos** [pandier/intellij-discord-rp#64]
please change the C# icon to this one with purple color
![net-framework-c-net-core-software-framework-mono-studio-thumbnail](https://github.com/pandier/intellij-discord-rp/assets/95594927/feba9251-ea10-40a3-8c7c-8ddb63555f82)

If this is not possible, please change the current one to dark purple instead of green.

**Comment by Cleboost** [comment]
In my opinion, it breaks the style of the other minimalist icons.

**Comment by DenianRamos** [comment]
You're right, I think it would be better to change the color to purple.

**Comment by pandier** [comment]
What do you think about this?

![csharp256](https://github.com/pandier/intellij-discord-rp/assets/62116820/c0ccb790-4e46-4091-aaf4-9cd19b086315)

**Comment by pandier** [comment]
Will be available in **1.3**.
