### ISSUE TITLE
Icon request for SQL

### ISSUE THREAD

**Issue by Cleboost** [pandier/intellij-discord-rp#72]
![image](https://github.com/pandier/intellij-discord-rp/assets/61158869/d27a05c7-bc42-4044-ad15-70a429038551)

**Comment by pandier** [comment]
Design proposal, wasn't sure about the color, so give me your thoughts:

![sql256](https://github.com/pandier/intellij-discord-rp/assets/62116820/d9998578-b0ef-4cb4-a687-1156034b7c70)

**Comment by Cleboost** [comment]
not sure about the color x) but black icon is perfect

**Comment by pandier** [comment]
Hmm, what about this?

![sql256](https://github.com/pandier/intellij-discord-rp/assets/62116820/ec555441-c009-44aa-8e70-6113320b6872)

**Comment by Cleboost** [comment]
This is better color \:)
