### ISSUE TITLE
Icon request for Prisma

### ISSUE THREAD

**Issue by Cleboost** [pandier/intellij-discord-rp#73]
![image](https://github.com/pandier/intellij-discord-rp/assets/61158869/ce00182f-6b36-4b22-b81e-89180b982387)
![image](https://github.com/pandier/intellij-discord-rp/assets/61158869/84d869a9-9f0c-4506-99dd-c21b3b27b423)
https://www.prisma.io

**Comment by pandier** [comment]
Design proposal:
