### ISSUE TITLE
Icon request for Licence

### ISSUE THREAD

**Issue by Cleboost** [pandier/intellij-discord-rp#74]
![image](https://github.com/pandier/intellij-discord-rp/assets/61158869/1aa72411-7ea8-4937-8b62-fe0fc620777e)
![image](https://github.com/pandier/intellij-discord-rp/assets/61158869/6ff0ec23-b563-4b17-9787-1f6b82afca3f)

**Comment by pandier** [comment]
What are all the ways a license file might be named? I currently have this case insensitive regex `^license(\.(md|txt))?$`.

**Comment by Cleboost** [comment]
The icon is perfect, in my memory Github always names licenses like that. Maybe modify the regex later if we get ideas, but for now it looks good.
