### ISSUE TITLE
Icon request for woff2 (font)

### ISSUE THREAD

**Issue by Cleboost** [pandier/intellij-discord-rp#75]
![image](https://github.com/pandier/intellij-discord-rp/assets/61158869/27229392-8474-457a-a0f7-063a9e1d96cb)
![image](https://github.com/pandier/intellij-discord-rp/assets/61158869/f5a66ff3-51be-402c-9f5d-40af841f69e7)

**Comment by pandier** [comment]
Can you describe some scenarios where it would be used (when would you open a font file in IntelliJ)?

**Comment by pandier** [comment]
I don't think the plugin would benefit from adding an icon for fonts. The icons should primarily be for languages and stuff related to those languages.
