### ISSUE TITLE
Icon request for Shell

### ISSUE THREAD

**Issue by Cleboost** [pandier/intellij-discord-rp#76]
![image](https://github.com/pandier/intellij-discord-rp/assets/61158869/c0448b49-ad4c-434f-9db9-9fa6fd4b62b0)
![image](https://github.com/pandier/intellij-discord-rp/assets/61158869/75dd359c-3253-4c57-b980-1a19c1e35abb)

**Comment by pandier** [comment]
Design proposal:

![shell](https://github.com/pandier/intellij-discord-rp/assets/62116820/42fe8bad-8710-4e9f-83fb-4531aeab7df4)

**Comment by Cleboost** [comment]
Perfect
