### ISSUE TITLE
Icon request for Batch

### ISSUE THREAD

**Issue by Cleboost** [pandier/intellij-discord-rp#77]
![image](https://github.com/pandier/intellij-discord-rp/assets/61158869/ce86dd7f-daac-4be3-aae1-3968450054a3)
![image](https://github.com/pandier/intellij-discord-rp/assets/61158869/99a34423-9c46-4e44-bc50-cd1e022efdad)

**Comment by Cleboost** [comment]
Same logo for .exe i think

![image](https://github.com/pandier/intellij-discord-rp/assets/61158869/ecac44af-56cd-4533-a9e9-bb210c5a7289)

**Comment by Cleboost** [comment]
I'm not sure... Then the logo itself is nice, but it lacks a reminder of Windows.

**Comment by pandier** [comment]
What would you suggest if we don't take the `.exe` into account, because it would not be very useful?

**Comment by Cleboost** [comment]
Maybe a Windows logo instead of the gear.

**Comment by pandier** [comment]
Here are some concepts with the Windows logo, what do you think?

![batch](https://github.com/pandier/intellij-discord-rp/assets/62116820/983d3262-8783-469b-b949-0bc389679d8f)

![batch_1](https://github.com/pandier/intellij-discord-rp/assets/62116820/5430f395-0e28-4ca9-bc2d-277b6331223f)

**Comment by Cleboost** [comment]
Sorry for delay,
First is perfect i think
