### ISSUE TITLE
Icon request for Visual Basic (.vb)

### ISSUE THREAD

**Issue by Cleboost** [pandier/intellij-discord-rp#78]
![image](https://github.com/pandier/intellij-discord-rp/assets/61158869/fc720769-f9ab-46a9-8210-5a4774479eea)
![image](https://github.com/pandier/intellij-discord-rp/assets/61158869/f285e223-908d-4c08-bdec-51f498d35f91)

**Comment by pandier** [comment]
Design proposal:

![visualbasic256](https://github.com/pandier/intellij-discord-rp/assets/62116820/24adf4ad-d818-4e00-878c-995cad6fc9a1)

**Comment by Cleboost** [comment]
Clean
