### ISSUE TITLE
Icon request for binary

### ISSUE THREAD

**Issue by Cleboost** [pandier/intellij-discord-rp#79]
Design with 0 and 1 black on yellow-orange (in my mind)

![image](https://github.com/pandier/intellij-discord-rp/assets/61158869/f34a8d5c-731f-4980-8a4a-a24b9a815e5e)
![image](https://github.com/pandier/intellij-discord-rp/assets/61158869/37edb8ac-2859-4952-ace7-88ae919fe17f)

**Comment by pandier** [comment]
Does the plugin need an icon for binary files? I don't see a reason why you would open a binary file in IntelliJ. Can you give me some examples?

**Comment by Cleboost** [comment]
If you want to obtain the raw data from a binary, it can be opened.

**Comment by pandier** [comment]
I think the default icon might be sufficient enough. Binary isn't necessarily the format of the file, but how the data is represented.

**Comment by Cleboost** [comment]
Okay !
