### ISSUE TITLE
 C Language Files Aren't Being Discovered by Rich Presence

### ISSUE THREAD

**Issue by 1plam** [pandier/intellij-discord-rp#80]
## Description:

Whenever you open a `.c` file, the Discord Rich Presence ignores it, resulting in the last supported file being displayed instead. If you open the IDE directly on a `.c` file (without previously opening a supported file type), no Rich Presence activity occurs at all.

## Steps to Reproduce:

1. Open any supported file type and verify that Rich Presence updates accordingly.
2. Open a `.c` file. Note that Rich Presence continues to display the last supported file instead of the `.c` file.
3. Close the IDE and reopen it directly with a `.c` file. Note that Rich Presence does not activate.

## Showcase:

![sample](https://github.com/pandier/intellij-discord-rp/assets/77026826/11debd33-e658-4a04-9b3d-9aa78c0adce7)

### Expected behaviour

Rich Presence should correctly recognize and display `.c` files just like any other supported file type.

### What version of the plugin are you using?

1.3.0

### What IDE and version are you using?

CLion 2024.1.1

**Comment by pandier** [comment]
Can confirm this happens, the issue is that Discord requires the text to be at least two characters large, but the plugin tries to only put "C" which is not valid.

**Comment by pandier** [comment]
Fixed in version **1.3.1** which has now been released and will be available on the JetBrains Marketplace in the next 2 business days. Until then it can be downloaded through [GitHub Releases](https://github.com/pandier/intellij-discord-rp/releases/tag/v1.3.1).
