### ISSUE TITLE
Icon request for HTTP

### ISSUE THREAD

**Issue by 1plam** [pandier/intellij-discord-rp#82]
## Description

Not sure which specific icon could suit this request, but having it would be nice!

## To be Requested

![image](https://github.com/pandier/intellij-discord-rp/assets/77026826/22f05e8c-e637-4789-9b32-77d1693d9344)
![image](https://github.com/pandier/intellij-discord-rp/assets/77026826/45f28ae0-67fe-494b-a498-cf8c65aac678)

**Comment by pandier** [comment]
I tried a couple of different things and I feel like just "HTTP" text would be the best:

![http256](https://github.com/pandier/intellij-discord-rp/assets/62116820/cd3a9ff4-d43d-45db-899f-eea1af515875)

**Comment by 1plam** [comment]
Looks great!

**Comment by pandier** [comment]
Will be available in version **1.4**
