### ISSUE TITLE
Become build 242.* compatible

### ISSUE THREAD

**Issue by Cleboost** [pandier/intellij-discord-rp#83]
### What's missing?

![image](https://github.com/pandier/intellij-discord-rp/assets/61158869/b1cbb58b-05d7-4752-a3d0-dc4a8a04f5c9)
![image](https://github.com/pandier/intellij-discord-rp/assets/61158869/9660a632-6f67-4a06-a876-d8405ecd2094)

**Comment by pandier** [comment]
Should be compatible now, can you check it?

**Comment by Cleboost** [comment]
Need to do update ?
![image](https://github.com/pandier/intellij-discord-rp/assets/61158869/018597a6-337f-4b34-83d0-cd2d965b18b4)

**Comment by pandier** [comment]
Should work when **1.3.2** becomes available
