### ISSUE TITLE
Icon request for F#

### ISSUE THREAD

**Issue by 1plam** [pandier/intellij-discord-rp#84]
![CleanShot 2024-05-30 at 22 05 00@2x](https://github.com/pandier/intellij-discord-rp/assets/77026826/f48d79db-0fb9-4e7a-88fa-77b20e73fef9)

**Comment by Cleboost** [comment]
What is fs ? I don't find any logo exemple on google.

**Comment by 1plam** [comment]
> What is fs ? I don't find any logo exemple on google.

https://learn.microsoft.com/en-us/dotnet/fsharp/

**Comment by pandier** [comment]
Design proposal:

![fsharp](https://github.com/pandier/intellij-discord-rp/assets/62116820/c5cca66d-fad6-4f04-847b-299df5c970e5)

**Comment by 1plam** [comment]
Looks good to me!

**Comment by pandier** [comment]
Released in **1.4.0**, it should take around two business days until it gets approved on JetBrains Marketplace. Until then it can be downloaded through GitHub Releases.
