### ISSUE TITLE
Icon request for .proto

### ISSUE THREAD

**Issue by 1plam** [pandier/intellij-discord-rp#86]
`.proto` files are a must for gRPC framework that enables client and server applications to communicate transparently, and simplifies the building of connected systems.

![danek 2024-06-17 at 9  39 19](https://github.com/pandier/intellij-discord-rp/assets/77026826/917ef9d9-569e-4491-8621-df1dfef645cb)

Thanks in advance!

**Comment by pandier** [comment]
Design proposal:

![protobuf](https://github.com/pandier/intellij-discord-rp/assets/62116820/707627a0-a826-450f-a572-4cc3b606b8b5)

**Comment by 1plam** [comment]
Clean!
