### ISSUE TITLE
Icon request for .env

### ISSUE THREAD

**Issue by Cleboost** [pandier/intellij-discord-rp#87]
![image](https://github.com/user-attachments/assets/c56298bd-1069-4b6c-99a9-65eb7114af3a)

**Comment by Cleboost** [comment]
No idea :sweat_smile:

**Comment by pandier** [comment]
There are couple ideas that came to mind:

- An icon with a gear in it, or generally something with a gear
- An icon with a key, because `.env` files usually hold sensitive information

**Comment by Cleboost** [comment]
I think key is better. `.env` is more usually used for sensitives informations.

**Comment by pandier** [comment]
Here is my proposed designs, what do you think is the best?

![env@ 5x](https://github.com/user-attachments/assets/0d596915-bfe2-4b7e-a1e5-8ffe1c4c4bdd)
![env@ 5x-1](https://github.com/user-attachments/assets/1ad222e0-d7a9-4000-8999-a3dd916af4b8)
![env@ 5x-2](https://github.com/user-attachments/assets/07388545-2f2f-4849-ab89-1a06e9a176c1)

The 1st one matches with my original icons for Java and Kotlin, so I would personally choose that one. Changing the color is also an option. Here is a cyan color that I think also works (I only used the first one, but any combination can be made):

![env@ 5x](https://github.com/user-attachments/assets/29b31fae-f648-422f-a5f6-c5d41bd81eaf)

**Comment by Cleboost** [comment]
The cyan is a good option I think
