### ISSUE TITLE
Icon request for JSX/TSX

### ISSUE THREAD

**Issue by RickyC0626** [pandier/intellij-discord-rp#91]
**File extension:** `.jsx`, `.tsx`

Originally used for React, but has since been used by many other frameworks (Vue babel plugin for JSX, Preact, Qwik, Inferno, Hyperapp).

Here's a variation of what it could look like, logo is released under Creative Commons license
https://github.com/OpenJSX/logo

<img src="https://github.com/user-attachments/assets/4042987e-c891-49fc-a658-933e884ef4e8" height="256" width="256" />

Or perhaps showing what makes JSX distinct by displaying the brackets `{<JSX>}`

![image](https://github.com/user-attachments/assets/d109f129-b4c7-443c-a6e2-f0576e2c1ac2)

**Comment by pandier** [comment]
Sorry, I might not be able to work on the plugin for a few days. I'll add it as soon as I can

**Comment by RickyC0626** [comment]
> Sorry, I might not be able to work on the plugin for a few days. I'll add it as soon as I can

No worries, just throwing ideas out there. Take your time.

**Comment by pandier** [comment]
I had a few ideas for this one, here are them executed:

![jsx1](https://github.com/user-attachments/assets/5ef1c1ed-f1bc-432b-ac5b-05cf1dce5630)
![jsx2a](https://github.com/user-attachments/assets/4f5b741c-cac9-4b3e-8fff-12dfb37713ff)
![jsx2b](https://github.com/user-attachments/assets/b93a6f7c-6504-44e0-a34b-3b7d1553a5f9)
![jsx2c](https://github.com/user-attachments/assets/28cba5a6-204d-48a8-bda2-976b70c0188b)
![jsx3](https://github.com/user-attachments/assets/a0e7b47a-5f1e-416e-8945-318ec9cefede)

Let me know what you think!

**Comment by Cleboost** [comment]
Personally, I prefer the first

**Comment by RickyC0626** [comment]
> Personally, I prefer the first

Same, first one has more impact with the brackets. I wonder how TSX would look?

**Comment by pandier** [comment]
Here's how TSX would look like with the same design idea:

![tsx1@ 5x](https://github.com/user-attachments/assets/815204db-8d90-4211-b68d-0393cc187ef3)
