### ISSUE TITLE
DiscordRichPresencePlugin - Could not find any Discord client instance

### ISSUE THREAD

**Issue by hellohate** [pandier/intellij-discord-rp#92]
### What happened?

Hi i`m using arch linux as my main system
```bash
                   -`                    levixgod@archzakhar
                  .o+`                   -------------------
                 `ooo/                   OS: Arch Linux x86_64
                `+oooo:                  Host: HP ProBook 445 G7 SBKPF
               `+oooooo:                 Kernel: 6.10.5-arch1-1
               -+oooooo+:                Uptime: 11 hours, 12 mins
             `/:-:++oooo+:               Packages: 945 (pacman), 26 (flatpak)
            `/++++/+++++++:              Shell: zsh 5.9
           `/++++++++++++++:             Resolution: 1920x1080
          `/+++ooooooooooooo/`           DE: GNOME 46.4
         ./ooosssso++osssssso+`          WM: Mutter
        .oossssso-````/ossssss+`         WM Theme: Orchis-Dark-Compact
       -osssssso.      :ssssssso.        Theme: Orchis-Dark-Compact [GTK2/3]
      :osssssss/        osssso+++.       Icons: Tela-dark [GTK2/3]
     /ossssssss/        +ssssooo/-       Terminal: WarpTerminal
   `/ossssso+/:-        -:/+osssso+-     CPU: AMD Ryzen 5 4500U with Radeon Graphi
  `+sso+:-`                 `.-/+oso:    GPU: AMD ATI Radeon Vega Series / Radeon
 `++:.                           `-/+/   Memory: 8228MiB / 15392MiB
 .`                                 `/
```

and when i try to use this plugin nothing hapens(
here`s my idea.log 
2024-08-19 23:38:38,729 [   5829]   INFO - #io.github.pandier.intellijdiscordrp.DiscordRichPresencePlugin - Could not find any Discord client instance

### What version of the plugin are you using?

1.4.1

### What IDE and version are you using?

intellij Idea PyCharm Professional 2024.2

**Comment by pandier** [comment]
Hi, how did you install Discord? (through flatpak or something else). Do you have Discord running when you start IntelliJ? If you are a bit more advanced, could you tell me where your Discord IPC file is located? (it's fine if you don't know)

**Comment by hellohate** [comment]
Hello i installed discord via Flathub(flatpak)
![image](https://github.com/user-attachments/assets/a88d23dc-82cd-4e68-8027-22f57a64ac86)
dk where the IPC file is located

**Comment by pandier** [comment]
Do you have the `XDG_RUNTIME_DIR` environment variable set up? What is its content? Can you check that a `discord-ipc-0` file (or any other files) is located in `/run/user/1000/app/com.discordapp.Discord`?

**Comment by hellohate** [comment]
echo $XDG_RUNTIME_DIR -> /run/user/1000
![image](https://github.com/user-attachments/assets/c0a7b122-e3c5-483a-9f3f-0ccfee5b3367)

**Comment by pandier** [comment]
Is Discord open when you checked the contents of that folder? If not, can you check it with Discord open?

**Comment by Cleboost** [comment]
A friend of mine had the same problem a few days ago using discord installed from flathub.
He solved his problem by doing these commands (they are used to specify the access path to the discord rpc. this would require a reboot i believe.)

```
mkdir -p ~/.config/user-tmpfiles.d
echo 'L %t/discord-ipc-0 - - - - app/com.discordapp.Discord/discord-ipc-0' > ~/.config/user-tmpfiles.d/discord-rpc.conf
systemctl --user enable --now systemd-tmpfiles-setup.service
```


if this solves your problem I'd add a line to the readme I think

**Comment by pandier** [comment]
Oh also, how did you install IntelliJ? Also through flatpak?

**Comment by hellohate** [comment]
yes also flatpak

**Comment by hellohate** [comment]
> A friend of mine had the same problem a few days ago using discord installed from flathub.
> He solved his problem by doing these commands (they are used to specify the access path to the discord rpc. this would require a reboot i believe.)

didn`t work for me(

**Comment by Cleboost** [comment]
It's weird. From what I understand, this command is used to link the flathub/pak discord application with the official package names to be recognized.

**Comment by Cleboost** [comment]
@codding-nepale

**Comment by codding-nepale** [comment]
Hi, you don't need to open the discord-ipc-0 file, but you do need to reopen the flathub discord application. If the commands I send you don't work, can you try telling me what the command:
```bash
flatpak run com.discordapp. Discord
```or send me the output directly, closing discord completely by clicking on the discord icon at the top right of Gnome if you're under Gnome and clicking on “Quit Discord” to close it completely. Always test using the CLI to start WebStorm, making sure the plugin is activated :) to see if you don't get an RPC error on Discord. If you want, you can also consult this page: https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-%28discord-rpc%29 which is where I found the commands to see if there's any further information for arch linux. If none of the solutions mentioned in this long message :) thank you for mentioning me again and I'll try to see more information for arch linux because I'm on Zorin OS which is an Ubuntu/Debian base.

Image of discord quit icon :

![image](https://github.com/user-attachments/assets/adfd259a-ebc7-4495-b045-8d8f5520b4fc)

**Comment by codding-nepale** [comment]
@hellohate hello, have you news ?

**Comment by pandier** [comment]
Closing the issue due to inactivity. Feel free to comment if there are any new updates and I'll reopen the issue.

**Comment by limpid-kzonix** [comment]
`/run/user/1000/.flatpak/com.discordapp.Discord/xdg-run/discord-ipc-0`

**Comment by limpid-kzonix** [comment]
The underlying library (`vyfor/KPresence`) does not respect updated path of runtime directories for a Flatpak installation. `.flatpak` reflects a move towards clearer and stricter namespace management for Flatpak applications, reducing the chances of conflicts with non-Flatpak applications. It seems that this was added recently.
