### ISSUE TITLE
Icon request for DB tool

### ISSUE THREAD

**Issue by Cleboost** [pandier/intellij-discord-rp#93]
When we're in webstorm's integrated DB viewer, we have no logo. I know this isn't a file, but if it's possible to integrate a logo for this, that would be cool. I'm thinking of a logo with a blackboard on a green background. I'll let you see what you can do ;)

![image](https://github.com/user-attachments/assets/9cf82060-33e8-4f64-a03d-94194056f48b)
![image](https://github.com/user-attachments/assets/14dd8cbb-7d61-475d-ab31-07762a6df633)

**Comment by pandier** [comment]
Here's the icon proposal:

![dbviewer@0 5x](https://github.com/user-attachments/assets/df841551-cefa-4025-9fe5-64fd4dbd2d37)

**Comment by Cleboost** [comment]
I'm OK 👌
