### ISSUE TITLE
Update IDE icon

### ISSUE THREAD

**Issue by Cleboost** [pandier/intellij-discord-rp#94]
Update icons when we do nothing in a project to the new ones

![image](https://github.com/user-attachments/assets/3049588c-b470-4f23-8fcb-fdbd9dfa57fb)
![image](https://github.com/user-attachments/assets/6854ea69-2336-4a30-a22d-8448cbc2f7a4)

**Comment by pandier** [comment]
Hmm, not everyone seems to like the new logos, I'm gonna make an option to switch between the old and the new ones
