### ISSUE TITLE
Icon request for Scala

### ISSUE THREAD

**Issue by meto1558** [pandier/intellij-discord-rp#99]
![Ekran Görüntüsü - 2024-10-01 13-20-35](https://github.com/user-attachments/assets/1382fc6e-30d6-4f67-8a09-3547ce6c243d)
Hi! I don't see Scala icon, can you add it?

**Comment by pandier** [comment]
Design proposal:

![scala@0 5x](https://github.com/user-attachments/assets/a8ea9c7d-399e-45ad-91d7-8f8a00ac4353)

**Comment by meto1558** [comment]
Very nice! Can I contribute or will you add it later?

**Comment by pandier** [comment]
Sorry, I had already added it by the time I sent the proposal, but I waited to push it until I got your feedback. The process of adding an icon to the plugin can be a bit confusing, especially since I haven't documented it yet, but I appreciate the offer!

**Comment by meto1558** [comment]
Okay, thank you! Have a nice day.
